-- ============================================================
-- SEED DATA: Initial content for site_content table
-- Run AFTER schema.sql. All rows inserted with status = 'published'
-- Safe to run multiple times — uses ON CONFLICT upsert
-- ============================================================

INSERT INTO site_content (section, content_key, locale, content_text, status) VALUES

-- ── Global: School Info ──
('global', 'schoolName', 'en', 'Kathmandu English School', 'published'),
('global', 'schoolName', 'ne', 'काठमाडौं इंग्लिश स्कूल', 'published'),
('global', 'schoolName', 'ja', 'カトマンズイングリッシュスクール', 'published'),
('global', 'motto', 'en', 'Learning is Endless', 'published'),
('global', 'motto', 'ne', 'सिकाइ अनन्त छ', 'published'),
('global', 'motto', 'ja', '学びは無限', 'published'),
('global', 'principalName', 'en', 'Mr. Dinesh Khatiwada', 'published'),
('global', 'principalName', 'ne', 'श्री दिनेश खतिवडा', 'published'),
('global', 'principalName', 'ja', 'ディネシュ・カティワダ氏', 'published'),
('global', 'principalMessage', 'en', 'At KES, we believe every child has limitless potential. Our goal is to provide a nurturing environment where students discover their unique talents and grow into responsible global citizens.', 'published'),
('global', 'principalMessage', 'ne', 'केईएसमा हामी हरेक बच्चामा असीमित सम्भावना हुन्छ भन्ने विश्वास गर्छौं।', 'published'),
('global', 'principalMessage', 'ja', 'KESでは、すべての子どもに無限の可能性があると信じています。', 'published'),

-- ── Global: Contact Info ──
('global', 'phone', 'en', '+977-1-4514369', 'published'),
('global', 'phone', 'ne', '+977-1-4514369', 'published'),
('global', 'phone', 'ja', '+977-1-4514369', 'published'),
('global', 'phone2', 'en', '+977-1-4514370', 'published'),
('global', 'phone2', 'ne', '+977-1-4514370', 'published'),
('global', 'phone2', 'ja', '+977-1-4514370', 'published'),
('global', 'email', 'en', 'info@kes.edu.np', 'published'),
('global', 'email', 'ne', 'info@kes.edu.np', 'published'),
('global', 'email', 'ja', 'info@kes.edu.np', 'published'),
('global', 'address', 'en', 'Naxal, Sanogaucharan, Mandev Marga, Kathmandu, Nepal', 'published'),
('global', 'address', 'ne', 'नक्साल, सानोगौचरण, मन्देब मार्ग, काठमाडौं, नेपाल', 'published'),
('global', 'address', 'ja', 'ナクサル、サノガウチャラン、マンデブ・マルガ、カトマンズ、ネパール', 'published'),

-- ── News Articles (6 articles, all 3 locales) ──
-- Article 1
('news', 'article_1_title', 'en', 'KES Students Top National Science Olympiad 2026', 'published'),
('news', 'article_1_title', 'ne', 'केईएसका विद्यार्थीहरू राष्ट्रिय विज्ञान ओलम्पियाड २०२६ मा शीर्ष स्थानमा', 'published'),
('news', 'article_1_title', 'ja', 'KESの生徒が全国科学オリンピック2026でトップに', 'published'),
('news', 'article_1_excerpt', 'en', 'Three KES students secured top positions at the National Science Olympiad.', 'published'),
('news', 'article_1_excerpt', 'ne', 'केईएसका तीन विद्यार्थीहरूले राष्ट्रिय विज्ञान ओलम्पियाडमा शीर्ष स्थान हासिल गरे।', 'published'),
('news', 'article_1_excerpt', 'ja', 'KESの3人の生徒が全国科学オリンピックで上位を獲得しました。', 'published'),
('news', 'article_1_content', 'en', 'Kathmandu English School is proud to announce that three of our students secured top positions at the National Science Olympiad 2026.', 'published'),
('news', 'article_1_content', 'ne', 'केईएस गर्वका साथ घोषणा गर्दछ कि हाम्रा तीन विद्यार्थीहरूले राष्ट्रिय विज्ञान ओलम्पियाडमा शीर्ष स्थान हासिल गरे।', 'published'),
('news', 'article_1_content', 'ja', 'KESは、2026年全国科学オリンピックで3人の生徒が上位を獲得したことを誇りを持って発表します。', 'published'),
('news', 'article_1_author', 'en', 'KES Media Team', 'published'),
('news', 'article_1_date', 'en', '2026-05-05', 'published'),
('news', 'article_1_image', 'en', 'https://picsum.photos/seed/kesnews1/800/600', 'published'),
('news', 'article_1_category', 'en', 'Achievement', 'published'),
('news', 'article_1_slug', 'en', 'kes-tops-national-science-olympiad-2026', 'published'),
('news', 'article_1_tags', 'en', '["science","olympiad","achievement","national"]', 'published'),

-- Article 2
('news', 'article_2_title', 'en', 'State-of-the-Art Computer Lab Inaugurated by Education Minister', 'published'),
('news', 'article_2_title', 'ne', 'शिक्षा मन्त्रीद्वारा अत्याधुनिक कम्प्युटर प्रयोगशालाको उद्घाटन', 'published'),
('news', 'article_2_title', 'ja', '教育大臣により最先端コンピューターラボが開設', 'published'),
('news', 'article_2_excerpt', 'en', 'Education Minister inaugurated our newly upgraded computer lab featuring 40 high-tech workstations.', 'published'),
('news', 'article_2_excerpt', 'ne', 'शिक्षा मन्त्रीले ४० उच्च-प्रविधि कम्प्युटरसहित नयाँ प्रयोगशालाको उद्घाटन गर्नुभयो।', 'published'),
('news', 'article_2_excerpt', 'ja', '教育大臣が40台のハイテクワークステーションを備えた新ラボを開設しました。', 'published'),
('news', 'article_2_content', 'en', 'A new chapter in digital learning began at KES as the Education Minister inaugurated our state-of-the-art computer laboratory.', 'published'),
('news', 'article_2_content', 'ne', 'डिजिटल सिकाइको नयाँ अध्याय सुरु भयो।', 'published'),
('news', 'article_2_content', 'ja', 'デジタル学習の新たな章が始まりました。', 'published'),
('news', 'article_2_author', 'en', 'KES Media Team', 'published'),
('news', 'article_2_date', 'en', '2026-04-20', 'published'),
('news', 'article_2_image', 'en', 'https://picsum.photos/seed/kesnews2/800/600', 'published'),
('news', 'article_2_category', 'en', 'Infrastructure', 'published'),
('news', 'article_2_slug', 'en', 'new-computer-lab-inauguration-ceremony', 'published'),
('news', 'article_2_tags', 'en', '["computer-lab","technology","infrastructure"]', 'published'),

-- Article 3
('news', 'article_3_title', 'en', 'KES Launches Scholarship Program for Underprivileged Students', 'published'),
('news', 'article_3_title', 'ne', 'केईएसले विपन्न विद्यार्थीहरूका लागि छात्रवृत्ति कार्यक्रम सुरु गर्यो', 'published'),
('news', 'article_3_title', 'ja', 'KESが経済的困難を抱える生徒向け奨学金プログラムを開始', 'published'),
('news', 'article_3_excerpt', 'en', 'Twenty full scholarships announced for meritorious students from economically disadvantaged backgrounds.', 'published'),
('news', 'article_3_excerpt', 'ne', 'आर्थिक रूपमा विपन्न मेधावी विद्यार्थीहरूका लागि बीस पूर्ण छात्रवृत्तिहरू घोषणा।', 'published'),
('news', 'article_3_excerpt', 'ja', '経済的困難を抱える優秀な学生向けに20の全額奨学金が発表されました。', 'published'),
('news', 'article_3_content', 'en', 'KES has launched a comprehensive scholarship initiative for meritorious students from disadvantaged backgrounds.', 'published'),
('news', 'article_3_content', 'ne', 'केईएसले विपन्न पृष्ठभूमिका मेधावी विद्यार्थीहरूका लागि व्यापक छात्रवृत्ति पहल सुरु गरेको छ।', 'published'),
('news', 'article_3_content', 'ja', 'KESは経済的困難を抱える優秀な学生のための包括的な奨学金イニシアチブを開始しました。', 'published'),
('news', 'article_3_author', 'en', 'KES Admin', 'published'),
('news', 'article_3_date', 'en', '2026-04-10', 'published'),
('news', 'article_3_image', 'en', 'https://picsum.photos/seed/kesnews3/800/600', 'published'),
('news', 'article_3_category', 'en', 'Announcement', 'published'),
('news', 'article_3_slug', 'en', 'kes-launches-scholarship-program-for-underprivileged', 'published'),
('news', 'article_3_tags', 'en', '["scholarship","community","announcement"]', 'published'),

-- Article 4
('news', 'article_4_title', 'en', 'KES Debate Team Clinches Inter-School Championship Trophy', 'published'),
('news', 'article_4_title', 'ne', 'केईएस वादविवाद टोलीले अन्तर-विद्यालय च्याम्पियनसिप ट्रफी जित्यो', 'published'),
('news', 'article_4_title', 'ja', 'KESディベートチームが学校対抗選手権トロフィーを獲得', 'published'),
('news', 'article_4_excerpt', 'en', 'Our debate team won the prestigious Kathmandu Valley Inter-School Debate Championship.', 'published'),
('news', 'article_4_excerpt', 'ne', 'हाम्रो वादविवाद टोलीले प्रतिष्ठित काठमाडौं उपत्यका अन्तर-विद्यालय वादविवाद च्याम्पियनसिप जित्यो।', 'published'),
('news', 'article_4_excerpt', 'ja', 'ディベートチームが名門カトマンズバレー学校対抗ディベート選手権で優勝しました。', 'published'),
('news', 'article_4_content', 'en', 'The KES Debate Team emerged victorious at the Kathmandu Valley Inter-School Debate Championship.', 'published'),
('news', 'article_4_content', 'ne', 'केईएस वादविवाद टोलीले काठमाडौं उपत्यका अन्तर-विद्यालय वादविवाद च्याम्पियनसिपमा विजय हासिल गरेको छ।', 'published'),
('news', 'article_4_content', 'ja', 'KESディベートチームがカトマンズバレー学校対抗ディベート選手権で優勝しました。', 'published'),
('news', 'article_4_author', 'en', 'KES Media Team', 'published'),
('news', 'article_4_date', 'en', '2026-03-28', 'published'),
('news', 'article_4_image', 'en', 'https://picsum.photos/seed/kesnews4/800/600', 'published'),
('news', 'article_4_category', 'en', 'Achievement', 'published'),
('news', 'article_4_slug', 'en', 'kes-wins-inter-school-debate-championship', 'published'),
('news', 'article_4_tags', 'en', '["debate","competition","achievement"]', 'published'),

-- Article 5
('news', 'article_5_title', 'en', 'KES Hosts International Exchange Students from Japan', 'published'),
('news', 'article_5_title', 'ne', 'केईएसले जापानबाट अन्तर्राष्ट्रिय आदानप्रदान विद्यार्थीहरूलाई आतिथ्यता प्रदान गर्यो', 'published'),
('news', 'article_5_title', 'ja', 'KESが日本からの国際交流学生を受け入れ', 'published'),
('news', 'article_5_excerpt', 'en', 'Fifteen students from Tokyo Sakura High School spent two weeks at KES for cultural exchange.', 'published'),
('news', 'article_5_excerpt', 'ne', 'टोकियो साकुरा हाई स्कूलका १५ विद्यार्थीहरूले केईएसमा दुई हप्ता बिताए।', 'published'),
('news', 'article_5_excerpt', 'ja', '東京桜高校から15人の学生がKESで2週間の文化交流を行いました。', 'published'),
('news', 'article_5_content', 'en', 'KES welcomed 15 students and 2 teachers from Tokyo for a two-week cultural exchange program.', 'published'),
('news', 'article_5_content', 'ne', 'केईएसले टोकियोबाट १५ विद्यार्थी र २ शिक्षकलाई दुई हप्ताको सांस्कृतिक आदानप्रदान कार्यक्रमका लागि स्वागत गर्यो।', 'published'),
('news', 'article_5_content', 'ja', 'KESは東京から15人の学生と2人の教師を2週間の文化交流プログラムに迎えました。', 'published'),
('news', 'article_5_author', 'en', 'KES Media Team', 'published'),
('news', 'article_5_date', 'en', '2026-03-15', 'published'),
('news', 'article_5_image', 'en', 'https://picsum.photos/seed/kesnews5/800/600', 'published'),
('news', 'article_5_category', 'en', 'Event', 'published'),
('news', 'article_5_slug', 'en', 'kes-hosts-international-exchange-students', 'published'),
('news', 'article_5_tags', 'en', '["exchange","international","culture","japan"]', 'published'),

-- Article 6
('news', 'article_6_title', 'en', 'KES Launches Comprehensive Mental Health & Wellness Program', 'published'),
('news', 'article_6_title', 'ne', 'केईएसले व्यापक मानसिक स्वास्थ्य र कल्याण कार्यक्रम सुरु गर्यो', 'published'),
('news', 'article_6_title', 'ja', 'KESが包括的なメンタルヘルス＆ウェルネスプログラムを開始', 'published'),
('news', 'article_6_excerpt', 'en', 'Full-time school counselor and weekly wellness sessions introduced for student mental health.', 'published'),
('news', 'article_6_excerpt', 'ne', 'विद्यार्थी मानसिक स्वास्थ्यका लागि पूर्णकालिक परामर्शदाता र साप्ताहिक कल्याण सत्रहरू सुरु।', 'published'),
('news', 'article_6_excerpt', 'ja', '生徒のメンタルヘルス支援のため常勤カウンセラーと週次セッションを導入。', 'published'),
('news', 'article_6_content', 'en', 'Recognizing the importance of mental health, KES has launched a comprehensive Mental Health & Wellness Program.', 'published'),
('news', 'article_6_content', 'ne', 'मानसिक स्वास्थ्यको महत्त्व बुझ्दै केईएसले व्यापक मानसिक स्वास्थ्य तथा कल्याण कार्यक्रम सुरु गरेको छ।', 'published'),
('news', 'article_6_content', 'ja', 'メンタルヘルスの重要性を認識し、KESは包括的なメンタルヘルス＆ウェルネスプログラムを開始しました。', 'published'),
('news', 'article_6_author', 'en', 'KES Admin', 'published'),
('news', 'article_6_date', 'en', '2026-03-01', 'published'),
('news', 'article_6_image', 'en', 'https://picsum.photos/seed/kesnews6/800/600', 'published'),
('news', 'article_6_category', 'en', 'Announcement', 'published'),
('news', 'article_6_slug', 'en', 'kes-implements-mental-health-wellness-program', 'published'),
('news', 'article_6_tags', 'en', '["mental-health","wellness","counseling"]', 'published'),

-- ── Footer ──
('footer', 'about', 'en', 'Kathmandu English School is a premier educational institution in Nepal, committed to academic excellence and holistic development since 1995.', 'published'),
('footer', 'about', 'ne', 'काठमाडौं इंग्लिश स्कूल सन् १९९५ देखि शैक्षिक उत्कृष्टता र समग्र विकासका लागि प्रतिबद्ध नेपालको एक प्रमुख शैक्षिक संस्था हो।', 'published'),
('footer', 'about', 'ja', 'カトマンズイングリッシュスクールは1995年以来、学業の卓越性と全人的発展に尽力するネパール有数の教育機関です。', 'published'),

-- ── Staff Members (seeded as individual keys) ──
('staff', 'staff_1_name', 'en', 'Mr. Dinesh Khatiwada', 'published'),
('staff', 'staff_1_designation', 'en', 'Principal', 'published'),
('staff', 'staff_1_photo', 'en', 'https://picsum.photos/seed/principal/300/300', 'published'),
('staff', 'staff_2_name', 'en', 'Mrs. Anju Thapa', 'published'),
('staff', 'staff_2_designation', 'en', 'Vice Principal', 'published'),
('staff', 'staff_2_photo', 'en', 'https://picsum.photos/seed/vp/300/300', 'published'),
('staff', 'staff_3_name', 'en', 'Mr. Rajan Koirala', 'published'),
('staff', 'staff_3_designation', 'en', 'Head of Department', 'published'),
('staff', 'staff_3_department', 'en', 'Science', 'published'),
('staff', 'staff_3_photo', 'en', 'https://picsum.photos/seed/science/300/300', 'published'),
('staff', 'staff_4_name', 'en', 'Mrs. Sunita Rai', 'published'),
('staff', 'staff_4_designation', 'en', 'Head of Department', 'published'),
('staff', 'staff_4_department', 'en', 'English', 'published'),
('staff', 'staff_4_photo', 'en', 'https://picsum.photos/seed/english/300/300', 'published'),
('staff', 'staff_5_name', 'en', 'Mr. Dhiraj Poudel', 'published'),
('staff', 'staff_5_designation', 'en', 'Head of Department', 'published'),
('staff', 'staff_5_department', 'en', 'Mathematics', 'published'),
('staff', 'staff_5_photo', 'en', 'https://picsum.photos/seed/math/300/300', 'published'),
('staff', 'staff_6_name', 'en', 'Mrs. Menuka Acharya', 'published'),
('staff', 'staff_6_designation', 'en', 'Head of Department', 'published'),
('staff', 'staff_6_department', 'en', 'Nepali', 'published'),
('staff', 'staff_6_photo', 'en', 'https://picsum.photos/seed/nepali/300/300', 'published'),
('staff', 'staff_7_name', 'en', 'Mr. Sagar Bista', 'published'),
('staff', 'staff_7_designation', 'en', 'Head of Department', 'published'),
('staff', 'staff_7_department', 'en', 'Computer Science', 'published'),
('staff', 'staff_7_photo', 'en', 'https://picsum.photos/seed/computer/300/300', 'published'),
('staff', 'staff_8_name', 'en', 'Mrs. Rajani Shrestha', 'published'),
('staff', 'staff_8_designation', 'en', 'Head of Department', 'published'),
('staff', 'staff_8_department', 'en', 'Social Studies', 'published'),
('staff', 'staff_8_photo', 'en', 'https://picsum.photos/seed/social/300/300', 'published'),

-- ── Testimonials ──
('testimonials', 'testimonial_1_text', 'en', 'KES has transformed my daughter into a confident and curious learner.', 'published'),
('testimonials', 'testimonial_1_text', 'ne', 'केईएसले मेरी छोरीलाई आत्मविश्वासी र जिज्ञासु विद्यार्थीमा रूपान्तरण गरेको छ।', 'published'),
('testimonials', 'testimonial_1_text', 'ja', 'KESは私の娘を自信に満ちた好奇心旺盛な学習者に変えました。', 'published'),
('testimonials', 'testimonial_1_name', 'en', 'Sunita Gurung', 'published'),
('testimonials', 'testimonial_1_role', 'en', 'Parent of Grade 8 Student', 'published'),
('testimonials', 'testimonial_1_image', 'en', 'https://picsum.photos/seed/kestest1/300/300', 'published'),
('testimonials', 'testimonial_2_text', 'en', 'The academic rigor and extracurricular balance at KES is outstanding.', 'published'),
('testimonials', 'testimonial_2_text', 'ne', 'केईएसमा शैक्षिक कठोरता र अतिरिक्त क्रियाकलापको सन्तुलन उत्कृष्ट छ।', 'published'),
('testimonials', 'testimonial_2_text', 'ja', 'KESでの学業の厳しさと課外活動のバランスは素晴らしいです。', 'published'),
('testimonials', 'testimonial_2_name', 'en', 'Rabin Shrestha', 'published'),
('testimonials', 'testimonial_2_role', 'en', 'Parent of Grade 10 Student', 'published'),
('testimonials', 'testimonial_2_image', 'en', 'https://picsum.photos/seed/kestest2/300/300', 'published'),
('testimonials', 'testimonial_3_text', 'en', 'The foundation I received at KES prepared me exceptionally well for higher education.', 'published'),
('testimonials', 'testimonial_3_text', 'ne', 'केईएसमा मैले पाएको आधारले मलाई उच्च शिक्षाका लागि असाधारण रूपमा तयार गर्यो।', 'published'),
('testimonials', 'testimonial_3_text', 'ja', 'KESで受けた基礎教育は高等教育に向けて非常に良い準備となりました。', 'published'),
('testimonials', 'testimonial_3_name', 'en', 'Aayusha Karki', 'published'),
('testimonials', 'testimonial_3_role', 'en', 'Alumna, Class of 2020', 'published'),
('testimonials', 'testimonial_3_image', 'en', 'https://picsum.photos/seed/kestest3/300/300', 'published'),
('testimonials', 'testimonial_4_text', 'en', 'What sets KES apart is its focus on character building alongside academics.', 'published'),
('testimonials', 'testimonial_4_text', 'ne', 'केईएसलाई अरूभन्दा फरक बनाउने कुरा भनेको शिक्षासँगै चरित्र निर्माणमा ध्यान हो।', 'published'),
('testimonials', 'testimonial_4_text', 'ja', 'KESを際立たせているのは、学業と並行した人格形成への注力です。', 'published'),
('testimonials', 'testimonial_4_name', 'en', 'Prakash Adhikari', 'published'),
('testimonials', 'testimonial_4_role', 'en', 'Parent of Grade 5 Student', 'published'),
('testimonials', 'testimonial_4_image', 'en', 'https://picsum.photos/seed/kestest4/300/300', 'published')

ON CONFLICT (section, content_key, locale) DO UPDATE SET
  content_text = EXCLUDED.content_text,
  status = 'published',
  updated_at = NOW();

-- ============================================================
-- SEED: Sample Career Application (for testing)
-- ============================================================
INSERT INTO career_applications (job_id, job_title, full_name, email, phone, address, dob, degree, university, experience_years, current_position, subjects, grades, cover_letter, status) VALUES
('job_1', 'Secondary Level Mathematics Teacher', 'Sita Adhikari', 'sita.adhikari@email.com', '+977-9841234567', 'Balaju, Kathmandu', '1995-03-15', 'M.Ed. Mathematics', 'Tribhuvan University', 4, 'Mathematics Teacher at XYZ School', 'Mathematics, Statistics', 'Grades 6-10', 'I am a passionate mathematics teacher with 4 years of experience in the NEB curriculum. I specialize in making complex concepts accessible through real-world examples and interactive activities.', 'pending'),
('job_2', 'Science Teacher (Physics Specialization)', 'Rajan Thapa', 'rajan.thapa@email.com', '+977-9851122334', 'Patan, Lalitpur', '1993-07-22', 'M.Sc. Physics', 'Kathmandu University', 3, 'Junior Physics Teacher', 'Physics, General Science', 'Grades 9-12', 'With a strong background in experimental physics and curriculum design, I am excited about the opportunity to contribute to the Science department at KES.', 'pending'),
('job_3', 'English Language Teacher', 'Anita Sharma', 'anita.sharma@email.com', '+977-9808765432', 'Baneshwor, Kathmandu', '1997-11-08', 'M.A. English Literature', 'Tribhuvan University', 1, 'English Tutor', 'English, Grammar, Literature', 'Grades 1-5', 'I believe in creating a fun and engaging English learning environment for young students. I am TEFL certified with Montessori training.', 'pending');
