import type { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  school: {
    name: "Kathmandu English School",
    shortName: "KES",
    motto: "Learning is Endless",
    established: 1995,
    history:
      "Founded in 1995, Kathmandu English School has been a beacon of quality education in Nepal. We are committed to nurturing young minds with a blend of academic excellence, cultural values, and modern pedagogy.",
    principal: {
      name: "Mr. Dinesh Khatiwada",
      message:
        "At KES, we believe every child has limitless potential. Our goal is to provide a nurturing environment where students discover their unique talents and grow into responsible global citizens.",
    },
  },

  contact: {
    address: "Naxal, Sanogaucharan, Mandev Marga, Kathmandu, Nepal",
    phone: "+977-1-4514369",
    phone2: "+977-1-4514370",
    email: "info@kes.edu.np",
    admissionsEmail: "admissions@kes.edu.np",
    mapEmbedUrl:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3532.125123456!2d85.331123!3d27.712345!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sNaxal%2C%20Kathmandu!5e0!3m2!1sen!2snp!4v1700000000000",
  },

  social: {
    facebook: "https://facebook.com/kesnepal",
    twitter: "https://twitter.com/kesnepal",
    youtube: "https://youtube.com/@kesnepal",
    instagram: "https://instagram.com/kesnepal",
  },

  nav: {
    links: [
      { label: "Home", href: "/" },
      { label: "About", href: "/about" },
      {
        label: "Academics",
        href: "/academics",
        dropdown: [
          { label: "Primary Level", href: "/academics#primary" },
          { label: "Secondary Level", href: "/academics#secondary" },
          { label: "Higher Secondary", href: "/academics#higher" },
          { label: "Faculty & Staff", href: "/academics#faculty" },
        ],
      },
      { label: "Admissions", href: "/admissions" },
      { label: "Results", href: "/results" },
      { label: "Gallery", href: "/gallery" },
      { label: "News", href: "/news" },
      { label: "Staff", href: "/staff" },
      { label: "Careers", href: "/careers" },
      { label: "Calendar", href: "/calendar" },
      { label: "Contact", href: "/contact" },
    ],
  },

  hero: {
    slides: [
      {
        image: "/images/hero/heroslide1.jpg",
        title: "Welcome to Kathmandu English School",
        subtitle: "Shaping Future Leaders Since 1995",
      },
      {
        image: "/images/hero/heroslide2.jpg",
        title: "Academic Excellence",
        subtitle: "Nurturing Inquisitive Minds with Modern Pedagogy",
      },
      {
        image: "/images/hero/heroslide3.jpg",
        title: "Holistic Development",
        subtitle: "Sports, Arts, and Cultural Programs for All-Round Growth",
      },
    ],
  },

  upcomingEvents: [
    {
      id: 1,
      title: "Annual Sports Meet 2083",
      date: "2026-06-15",
      time: "9:00 AM - 4:00 PM",
      location: "School Football Ground",
      image: "/images/events/event1.jpg",
      description:
        "Join us for three days of thrilling athletic competition. Students from Grade 3 to 12 will compete in track & field, team sports, and fun relays.",
    },
    {
      id: 2,
      title: "Science & Tech Exhibition",
      date: "2026-07-05",
      time: "10:00 AM - 3:00 PM",
      location: "School Auditorium",
      image: "/images/events/event2.jpg",
      description:
        "Students showcase innovative science projects, robotics demos, and tech prototypes. Parents and community members are welcome to attend.",
    },
    {
      id: 3,
      title: "Parent Orientation Day",
      date: "2026-05-28",
      time: "11:00 AM - 1:00 PM",
      location: "Main Assembly Hall",
      image: "/images/events/event3.jpg",
      description:
        "New parents are invited to meet the faculty, tour the campus, and learn about our curriculum, policies, and co-curricular programs.",
    },
    {
      id: 4,
      title: "Cultural Fest & Food Fair",
      date: "2026-08-12",
      time: "10:00 AM - 5:00 PM",
      location: "School Premises",
      image: "/images/events/event4.jpg",
      description:
        "Celebrate Nepal's rich diversity with cultural dances, music performances, food stalls, and art exhibitions by our talented students.",
    },
  ],

  newsArticles: [
    {
      id: 1,
      slug: "kes-tops-national-science-olympiad-2026",
      title: {
        en: "KES Students Top National Science Olympiad 2026",
        ne: "केईएसका विद्यार्थीहरू राष्ट्रिय विज्ञान ओलम्पियाड २०२६ मा शीर्ष स्थानमा",
        ja: "KESの生徒が全国科学オリンピック2026でトップに",
      },
      excerpt: {
        en: "Three KES students secured top positions at the National Science Olympiad, bringing home gold and silver medals in a nationwide competition.",
        ne: "केईएसका तीन विद्यार्थीहरूले राष्ट्रिय विज्ञान ओलम्पियाडमा शीर्ष स्थान हासिल गर्दै राष्ट्रव्यापी प्रतियोगितामा स्वर्ण र रजत पदक घर ल्याए।",
        ja: "KESの3人の生徒が全国科学オリンピックで上位を獲得し、全国大会で金メダルと銀メダルを獲得しました。",
      },
      content: {
        en: `Kathmandu English School is proud to announce that three of our students have secured top positions at the National Science Olympiad 2026 held in Kathmandu.\n\n**Gold Medal: Aryan Karki (Grade 10)**  \nAryan demonstrated exceptional knowledge in Physics and Chemistry, scoring 98 out of 100 in the final round. His project on "Renewable Energy Solutions for Rural Nepal" was highly praised by the jury.\n\n**Silver Medals: Sneha Pandey (Grade 9) and Roshan Tamang (Grade 10)**  \nSneha and Roshan both earned silver medals with their innovative approaches to Biology and Environmental Science respectively.\n\nThe Olympiad, organized by the Nepal Science Foundation, saw participation from over 200 schools across the country. Our students underwent weeks of rigorous preparation under the guidance of our dedicated Science faculty.\n\n"We are immensely proud of our students," said Principal Mr. Dinesh Khatiwada. "This achievement reflects the hard work of our students and the quality of education we strive to provide at KES."\n\nThe winners will now represent Nepal at the International Science Olympiad in Tokyo, Japan, later this year. The school has announced a special scholarship fund for the winners to support their advanced studies.`,
        ne: `[NE — translated content pending]\n\nKathmandu English School is proud to announce that three of our students have secured top positions at the National Science Olympiad 2026 held in Kathmandu.\n\n**Gold Medal: Aryan Karki (Grade 10)**  \n**Silver Medals: Sneha Pandey (Grade 9) and Roshan Tamang (Grade 10)**\n\nThe Olympiad, organized by the Nepal Science Foundation, saw participation from over 200 schools.\n\n"We are immensely proud of our students," said Principal Mr. Dinesh Khatiwada.\n\nThe winners will now represent Nepal at the International Science Olympiad in Tokyo, Japan.`,
        ja: `[JA — translated content pending]\n\nKathmandu English School is proud to announce that three of our students have secured top positions at the National Science Olympiad 2026 held in Kathmandu.\n\n**Gold Medal: Aryan Karki (Grade 10)**  \n**Silver Medals: Sneha Pandey (Grade 9) and Roshan Tamang (Grade 10)**\n\nThe Olympiad, organized by the Nepal Science Foundation, saw participation from over 200 schools.\n\n"We are immensely proud of our students," said Principal Mr. Dinesh Khatiwada.\n\nThe winners will now represent Nepal at the International Science Olympiad in Tokyo, Japan.`,
      },
      author: "KES Media Team",
      date: "2026-05-05",
      image: "/images/news/news1.jpg",
      category: "Achievement",
      tags: ["science", "olympiad", "achievement", "national"],
    },
    {
      id: 2,
      slug: "new-computer-lab-inauguration-ceremony",
      title: {
        en: "State-of-the-Art Computer Lab Inaugurated by Education Minister",
        ne: "शिक्षा मन्त्रीद्वारा अत्याधुनिक कम्प्युटर प्रयोगशालाको उद्घाटन",
        ja: "教育大臣により最先端コンピューターラボが開設",
      },
      excerpt: {
        en: "The Education Minister inaugurated our newly upgraded computer lab featuring 40 high-tech workstations and interactive learning tools.",
        ne: "शिक्षा मन्त्रीले ४० वटा उच्च-प्रविधियुक्त कम्प्युटर र अन्तरक्रियात्मक सिकाइ उपकरणहरू सहितको नयाँ कम्प्युटर प्रयोगशालाको उद्घाटन गर्नुभयो।",
        ja: "教育大臣が40台のハイテクワークステーションとインタラクティブな学習ツールを備えた新コンピューターラボを開設しました。",
      },
      content: {
        en: `A new chapter in digital learning began at Kathmandu English School as the Honorable Education Minister inaugurated our state-of-the-art computer laboratory on Chaitra 20, 2083.\n\nThe lab features:\n- **40 Apple M3 iMac workstations** with 24-inch displays\n- **High-speed fiber internet** (1 Gbps dedicated line)\n- **Interactive smart boards** for collaborative learning\n- **3D printer and robotics kits** for STEM education\n- **Licensed software** for coding, design, and office applications\n\nSpeaking at the ceremony, the Education Minister praised KES for its commitment to technology-integrated education. "Schools like KES are setting the benchmark for 21st-century learning in Nepal," he said.\n\nThe Chairman of KES emphasized that the lab will be open to students from all grades, with dedicated coding and robotics clubs starting from the next academic session.\n\nTeachers have already completed a 2-week training program on leveraging the new technology for enhanced classroom delivery.`,
        ne: `[NE] A new chapter in digital learning began at KES as the Education Minister inaugurated our state-of-the-art computer laboratory.\n\nThe lab features:\n- **40 Apple M3 iMac workstations**\n- **High-speed fiber internet**\n- **Interactive smart boards**\n- **3D printer and robotics kits**\n- **Licensed software**\n\n"Schools like KES are setting the benchmark for 21st-century learning in Nepal," said the Minister.\n\nTeachers have completed a 2-week training program on the new technology.`,
        ja: `[JA] A new chapter in digital learning began at KES as the Education Minister inaugurated our state-of-the-art computer laboratory.\n\nThe lab features:\n- **40 Apple M3 iMac workstations**\n- **High-speed fiber internet**\n- **Interactive smart boards**\n- **3D printer and robotics kits**\n- **Licensed software**\n\n"Schools like KES are setting the benchmark for 21st-century learning in Nepal," said the Minister.\n\nTeachers have completed a 2-week training program on the new technology.`,
      },
      author: "KES Media Team",
      date: "2026-04-20",
      image: "/images/news/news2.jpg",
      category: "Infrastructure",
      tags: ["computer-lab", "technology", "inauguration", "infrastructure"],
    },
    {
      id: 3,
      slug: "kes-launches-scholarship-program-for-underprivileged",
      title: {
        en: "KES Launches 'Udaan' Scholarship Program for Underprivileged Students",
        ne: "केईएसले विपन्न विद्यार्थीहरूका लागि 'उडान' छात्रवृत्ति कार्यक्रम सुरु गर्यो",
        ja: "KESが経済的困難を抱える生徒向け「Udaan」奨学金プログラムを開始",
      },
      excerpt: {
        en: "Twenty full scholarships announced for meritorious students from economically disadvantaged backgrounds across all seven provinces.",
        ne: "सातै प्रदेशका आर्थिक रूपमा विपन्न पृष्ठभूमिका मेधावी विद्यार्थीहरूका लागि बीस पूर्ण छात्रवृत्तिहरू घोषणा।",
        ja: "全7州の経済的困難を抱える優秀な学生向けに20の全額奨学金が発表されました。",
      },
      content: {
        en: `Kathmandu English School has launched the "Udaan Scholarship Program" — a comprehensive initiative to provide quality education to meritorious students from economically disadvantaged backgrounds.\n\n**Key Highlights:**\n- **20 Full Scholarships** awarded annually — 2 from each province plus 6 for Kathmandu Valley\n- Coverage includes tuition fees, books, uniform, meals, and transportation\n- **Special focus on girl child education** — 50% seats reserved for female students\n\nThe scholarship is merit-based and targets students entering Grade 6 and Grade 11. Selection will be through a transparent entrance examination followed by a family income verification process.\n\n"Our mission has always been to make quality education accessible," said the Chairman. "The Udaan program is our commitment to giving back to the community and nurturing talent."\n\nApplications for the 2083 academic session are now open. The last date for submission is Asar 30, 2083.`,
        ne: `[NE] Kathmandu English School has launched the "Udaan Scholarship Program" for meritorious students from economically disadvantaged backgrounds.\n\n**Key Highlights:**\n- **20 Full Scholarships** awarded annually\n- Coverage includes tuition, books, uniform, meals, transportation\n- **50% seats reserved for female students**\n\nApplications for 2083 are now open. Last date: Asar 30, 2083.`,
        ja: `[JA] Kathmandu English School has launched the "Udaan Scholarship Program" for meritorious students from economically disadvantaged backgrounds.\n\n**Key Highlights:**\n- **20 Full Scholarships** awarded annually\n- Coverage includes tuition, books, uniform, meals, transportation\n- **50% seats reserved for female students**\n\nApplications for 2083 are now open. Last date: Asar 30, 2083.`,
      },
      author: "KES Admin",
      date: "2026-04-10",
      image: "/images/news/news3.jpg",
      category: "Announcement",
      tags: ["scholarship", "community", "announcement", "accessibility"],
    },
    {
      id: 4,
      slug: "kes-wins-inter-school-debate-championship",
      title: {
        en: "KES Debate Team Clinches Inter-School Championship Trophy",
        ne: "केईएस वादविवाद टोलीले अन्तर-विद्यालय च्याम्पियनसिप ट्रफी जित्यो",
        ja: "KESディベートチームが学校対抗選手権トロフィーを獲得",
      },
      excerpt: {
        en: "Our debate team won the prestigious Kathmandu Valley Inter-School Debate Championship, defeating 32 schools in eloquent argumentation.",
        ne: "हाम्रो वादविवाद टोलीले ३२ विद्यालयहरूलाई पराजित गर्दै प्रतिष्ठित काठमाडौं उपत्यका अन्तर-विद्यालय वादविवाद च्याम्पियनसिप जित्यो।",
        ja: "私たちのディベートチームは、32校を破り、名門カトマンズバレー学校対抗ディベート選手権で優勝しました。",
      },
      content: {
        en: `The Kathmandu English School Debate Team has emerged victorious at the Kathmandu Valley Inter-School Debate Championship 2083, competing against 32 schools.\n\nThe championship spanned three rounds over two days. Our team, comprising **Srijana Adhikari (Grade 11)** — Best Speaker, **Kushal Basnet (Grade 10)**, and **Anisha Rai (Grade 10)**, demonstrated exceptional research and rebuttal skills.\n\n**Final Round Topic:** "Artificial Intelligence Will Do More Harm Than Good in Education"\n\nKES argued against the motion, presenting compelling arguments about AI's potential to personalize learning and bridge educational gaps in developing nations like Nepal.\n\nThe judging panel commended the team for their "well-researched arguments, calm demeanor, and impressive teamwork."\n\nKES will now represent Kathmandu Valley at the National Inter-School Debate Championship in Pokhara.`,
        ne: `[NE] The KES Debate Team has emerged victorious at the Kathmandu Valley Inter-School Debate Championship 2083, competing against 32 schools.\n\nOur team: **Srijana Adhikari (Grade 11)** — Best Speaker, **Kushal Basnet (Grade 10)**, **Anisha Rai (Grade 10)**.\n\n**Final Round Topic:** "Artificial Intelligence Will Do More Harm Than Good in Education"\n\nThe team was praised for their "well-researched arguments and impressive teamwork."\n\nKES will represent Kathmandu Valley at the National Championship in Pokhara.`,
        ja: `[JA] The KES Debate Team has emerged victorious at the Kathmandu Valley Inter-School Debate Championship 2083, competing against 32 schools.\n\nOur team: **Srijana Adhikari (Grade 11)** — Best Speaker, **Kushal Basnet (Grade 10)**, **Anisha Rai (Grade 10)**.\n\n**Final Round Topic:** "Artificial Intelligence Will Do More Harm Than Good in Education"\n\nThe team was praised for their "well-researched arguments and impressive teamwork."\n\nKES will represent Kathmandu Valley at the National Championship in Pokhara.`,
      },
      author: "KES Media Team",
      date: "2026-03-28",
      image: "/images/news/news4.jpg",
      category: "Achievement",
      tags: ["debate", "competition", "achievement", "trophy"],
    },
    {
      id: 5,
      slug: "kes-hosts-international-exchange-students",
      title: {
        en: "KES Hosts International Exchange Students from Japan",
        ne: "केईएसले जापानबाट अन्तर्राष्ट्रिय आदानप्रदान विद्यार्थीहरूलाई आतिथ्यता प्रदान गर्यो",
        ja: "KESが日本からの国際交流学生を受け入れ",
      },
      excerpt: {
        en: "Fifteen students from Tokyo's Sakura High School spent two weeks at KES as part of our cultural exchange program.",
        ne: "टोकियोको साकुरा हाई स्कूलका पन्ध्र विद्यार्थीहरूले हाम्रो सांस्कृतिक आदानप्रदान कार्यक्रम अन्तर्गत केईएसमा दुई हप्ता बिताए।",
        ja: "東京の桜高校から15人の学生が文化交流プログラムの一環としてKESで2週間過ごしました。",
      },
      content: {
        en: `Kathmandu English School welcomed 15 students and 2 teachers from Tokyo's Sakura High School for a two-week cultural exchange program.\n\nThe exchange program, now in its third year, included:\n- **Joint classroom sessions** on sustainable development\n- **Cultural workshops** — origami, calligraphy, Nepali folk dance, momo-making\n- **Field trips** to Bhaktapur, Swayambhunath, and Nagarkot\n- **Homestay program** with KES host families\n\n"It was an incredible experience," said Ayumi Tanaka, a Grade 10 student from Sakura High School. "I learned so much about Nepali culture."\n\nPlans are already underway for KES students to visit Tokyo next year.`,
        ne: `[NE] Kathmandu English School welcomed 15 students and 2 teachers from Tokyo's Sakura High School for a two-week cultural exchange program.\n\nThe program included:\n- **Joint classroom sessions**\n- **Cultural workshops** — origami, calligraphy, Nepali folk dance\n- **Field trips** to Bhaktapur, Swayambhunath, Nagarkot\n- **Homestay program**\n\n"It was an incredible experience," said Ayumi Tanaka. "I learned so much about Nepali culture."`,
        ja: `[JA] Kathmandu English School welcomed 15 students and 2 teachers from Tokyo's Sakura High School for a two-week cultural exchange program.\n\nThe program included:\n- **Joint classroom sessions**\n- **Cultural workshops** — origami, calligraphy, Nepali folk dance\n- **Field trips** to Bhaktapur, Swayambhunath, Nagarkot\n- **Homestay program**\n\n"It was an incredible experience," said Ayumi Tanaka. "I learned so much about Nepali culture."`,
      },
      author: "KES Media Team",
      date: "2026-03-15",
      image: "/images/news/news5.jpg",
      category: "Event",
      tags: ["exchange", "international", "culture", "japan"],
    },
    {
      id: 6,
      slug: "kes-implements-mental-health-wellness-program",
      title: {
        en: "KES Launches Comprehensive Mental Health & Wellness Program",
        ne: "केईएसले व्यापक मानसिक स्वास्थ्य र कल्याण कार्यक्रम सुरु गर्यो",
        ja: "KESが包括的なメンタルヘルス＆ウェルネスプログラムを開始",
      },
      excerpt: {
        en: "A full-time school counselor and weekly wellness sessions introduced to support student mental health and emotional well-being.",
        ne: "विद्यार्थीहरूको मानसिक स्वास्थ्य र भावनात्मक कल्याणलाई सहयोग गर्न पूर्णकालिक विद्यालय परामर्शदाता र साप्ताहिक कल्याण सत्रहरू सुरु गरियो।",
        ja: "生徒のメンタルヘルスと情緒的幸福を支援するため、常勤のスクールカウンセラーと週次のウェルネスセッションが導入されました。",
      },
      content: {
        en: `Recognizing the importance of mental health, KES has launched a comprehensive Mental Health & Wellness Program.\n\n**Program Components:**\n1. **Full-time School Counselor** — Licensed psychologist for one-on-one sessions\n2. **Weekly Wellness Sessions** — Stress management, mindfulness, emotional intelligence\n3. **Peer Support Network** — Trained student volunteers (Grade 10-12)\n4. **Parent Workshops** — Adolescent psychology and screen time management\n5. **Anti-Bullying Policy** — Zero-tolerance with restorative justice approach\n\n"Academic excellence means little without emotional well-being," said Ms. Sunita Rai, school counselor.\n\nKES is one of the first schools in Nepal to implement a structured mental health curriculum.`,
        ne: `[NE] Recognizing the importance of mental health, KES has launched a comprehensive Mental Health & Wellness Program.\n\n**Program Components:**\n1. **Full-time School Counselor**\n2. **Weekly Wellness Sessions**\n3. **Peer Support Network**\n4. **Parent Workshops**\n5. **Anti-Bullying Policy**\n\n"Academic excellence means little without emotional well-being," said Ms. Sunita Rai.\n\nKES is one of the first schools in Nepal with a structured mental health curriculum.`,
        ja: `[JA] Recognizing the importance of mental health, KES has launched a comprehensive Mental Health & Wellness Program.\n\n**Program Components:**\n1. **Full-time School Counselor**\n2. **Weekly Wellness Sessions**\n3. **Peer Support Network**\n4. **Parent Workshops**\n5. **Anti-Bullying Policy**\n\n"Academic excellence means little without emotional well-being," said Ms. Sunita Rai.\n\nKES is one of the first schools in Nepal with a structured mental health curriculum.`,
      },
      author: "KES Admin",
      date: "2026-03-01",
      image: "/images/news/news6.jpg",
      category: "Announcement",
      tags: ["mental-health", "wellness", "counseling", "student-support"],
    },
  ],

  testimonials: [
    {
      id: 1,
      name: "Sunita Gurung",
      role: "Parent of Grade 8 Student",
      image: "/images/testimonials/person1.jpg",
      text: "KES has transformed my daughter into a confident and curious learner. The teachers genuinely care about each child's development.",
    },
    {
      id: 2,
      name: "Rabin Shrestha",
      role: "Parent of Grade 10 Student",
      image: "/images/testimonials/person2.jpg",
      text: "The academic rigor and extracurricular balance at KES is outstanding. My son looks forward to school every single day.",
    },
    {
      id: 3,
      name: "Aayusha Karki",
      role: "Alumna, Class of 2020",
      image: "/images/testimonials/person3.jpg",
      text: "The foundation I received at KES prepared me exceptionally well for higher education. I am forever grateful.",
    },
    {
      id: 4,
      name: "Prakash Adhikari",
      role: "Parent of Grade 5 Student",
      image: "/images/testimonials/person4.jpg",
      text: "What sets KES apart is its focus on character building alongside academics. Truly a nurturing environment.",
    },
  ],

  gallery: {
    categories: ["Events", "Infrastructure", "Sports"],
    images: [
      { src: "https://picsum.photos/seed/school1/800/600", alt: "Annual Day Celebration", category: "Events", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/library/600/800", alt: "School Library", category: "Infrastructure", width: 600, height: 800 },
      { src: "https://picsum.photos/seed/sports1/800/600", alt: "Football Match", category: "Sports", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/science/800/600", alt: "Science Exhibition", category: "Events", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/computer/600/800", alt: "Computer Lab", category: "Infrastructure", width: 600, height: 800 },
      { src: "https://picsum.photos/seed/basketball/800/600", alt: "Basketball Tournament", category: "Sports", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/cultural/800/600", alt: "Cultural Program", category: "Events", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/auditorium/800/600", alt: "School Auditorium", category: "Infrastructure", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/swimming/600/800", alt: "Swimming Pool", category: "Sports", width: 600, height: 800 },
      { src: "https://picsum.photos/seed/art/800/600", alt: "Art Exhibition", category: "Events", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/playground/800/600", alt: "School Playground", category: "Infrastructure", width: 800, height: 600 },
      { src: "https://picsum.photos/seed/cricket/800/600", alt: "Cricket Tournament", category: "Sports", width: 800, height: 600 },
    ],
  },

  academicLevels: [
    {
      id: "primary",
      title: "Primary Level",
      grades: "Nursery - Grade 5",
      desc: "Our primary program focuses on building strong foundations in literacy, numeracy, and social skills through play-based and experiential learning methods. We follow a child-centric approach where every child learns at their own pace.",
      image: "/images/primary.jpg",
      subjects: ["English", "Nepali", "Mathematics", "Science", "Social Studies", "Computer", "Arts & Crafts", "Physical Education"],
    },
    {
      id: "secondary",
      title: "Secondary Level",
      grades: "Grade 6 - 10",
      desc: "The secondary curriculum deepens conceptual understanding and analytical skills. Students are prepared for the Secondary Education Examination (SEE) with rigorous academics and co-curricular enrichment.",
      image: "/images/secondary.jpg",
      subjects: ["English", "Nepali", "Mathematics", "Science", "Social Studies", "Computer Science", "Health & Physical Education", "Optional Subjects"],
    },
    {
      id: "higher",
      title: "Higher Secondary",
      grades: "Grade 11 - 12",
      desc: "Our 10+2 program offers Science and Management streams under NEB affiliation. Students receive advanced preparation for university entrance exams and career counseling.",
      image: "/images/higher.jpg",
      streams: [
        { name: "Science", subjects: ["Physics", "Chemistry", "Biology", "Mathematics", "English", "Computer Science"] },
        { name: "Management", subjects: ["Accountancy", "Economics", "Business Studies", "Mathematics", "English", "Computer Science"] },
      ],
    },
  ],

  faculty: [
    { name: "Mr. Bishnu Prasad Sharma", role: "Principal", dept: "Administration" },
    { name: "Mrs. Anju Thapa", role: "Vice Principal", dept: "Academics" },
    { name: "Mr. Rajan Koirala", role: "HOD", dept: "Science" },
    { name: "Mrs. Sunita Rai", role: "HOD", dept: "English" },
    { name: "Mr. Dhiraj Poudel", role: "HOD", dept: "Mathematics" },
    { name: "Mrs. Menuka Acharya", role: "HOD", dept: "Nepali" },
    { name: "Mr. Sagar Bista", role: "HOD", dept: "Computer Science" },
    { name: "Mrs. Rajani Shrestha", role: "HOD", dept: "Social Studies" },
  ],

  footer: {
    about:
      "Kathmandu English School is a premier educational institution in Nepal, committed to academic excellence and holistic development since 1995.",
    quickLinks: [
      { label: "About Us", href: "/about" },
      { label: "Admissions", href: "/admissions" },
      { label: "Academics", href: "/academics" },
      { label: "Our Team", href: "/staff" },
      { label: "Results", href: "/results" },
      { label: "Gallery", href: "/gallery" },
      { label: "News", href: "/news" },
      { label: "Careers", href: "/careers" },
      { label: "Calendar", href: "/calendar" },
      { label: "Contact Us", href: "/contact" },
    ],
  },

  staff: [
    {
      id: 1,
      name: "Mr. Dinesh Khatiwada",
      designation: "Principal",
      photo: "https://picsum.photos/seed/principal/300/300",
      department: "Administration",
    },
    {
      id: 2,
      name: "Mrs. Anju Thapa",
      designation: "Vice Principal",
      photo: "https://picsum.photos/seed/vp/300/300",
      department: "Academics",
    },
    {
      id: 3,
      name: "Mr. Rajan Koirala",
      designation: "Head of Department",
      photo: "https://picsum.photos/seed/science/300/300",
      department: "Science",
    },
    {
      id: 4,
      name: "Mrs. Sunita Rai",
      designation: "Head of Department",
      photo: "https://picsum.photos/seed/english/300/300",
      department: "English",
    },
    {
      id: 5,
      name: "Mr. Dhiraj Poudel",
      designation: "Head of Department",
      photo: "https://picsum.photos/seed/math/300/300",
      department: "Mathematics",
    },
    {
      id: 6,
      name: "Mrs. Menuka Acharya",
      designation: "Head of Department",
      photo: "https://picsum.photos/seed/nepali/300/300",
      department: "Nepali",
    },
    {
      id: 7,
      name: "Mr. Sagar Bista",
      designation: "Head of Department",
      photo: "https://picsum.photos/seed/computer/300/300",
      department: "Computer Science",
    },
    {
      id: 8,
      name: "Mrs. Rajani Shrestha",
      designation: "Head of Department",
      photo: "https://picsum.photos/seed/social/300/300",
      department: "Social Studies",
    },
  ],

  jobVacancies: [
    {
      id: 1,
      title: "Secondary Level Mathematics Teacher",
      category: "Teaching",
      level: "Secondary (Grade 6-10)",
      experience: "Minimum 3 years of teaching experience in a reputed school",
      salary: "Negotiable (Based on experience and qualification)",
      vacancies: 2,
      workstation: "Naxal, Sanogaucharan, Kathmandu",
      responsibilities: [
        "Plan and deliver engaging Mathematics lessons for Grade 6-10 following the NEB curriculum.",
        "Prepare lesson plans, assignments, and assessment papers in line with academic standards.",
        "Evaluate student performance through regular tests, quizzes, and examinations.",
        "Provide individual attention to weak students and conduct remedial classes.",
        "Participate in parent-teacher meetings and provide feedback on student progress.",
        "Contribute to the Mathematics department's resource development and curriculum planning.",
        "Mentor junior teachers and participate in professional development workshops.",
        "Maintain accurate student records including attendance, grades, and behavioral reports.",
      ],
      addedOn: "2026-05-01",
      expiresOn: "2026-06-15",
      isActive: true,
    },
    {
      id: 2,
      title: "Science Teacher (Physics Specialization)",
      category: "Teaching",
      level: "Secondary and Higher Secondary",
      experience: "Minimum 2 years of teaching Physics; fresh Master's graduates may apply",
      salary: "Negotiable (Based on experience and qualification)",
      vacancies: 1,
      workstation: "Naxal, Sanogaucharan, Kathmandu",
      responsibilities: [
        "Teach Physics theory and practical sessions to Grade 9-12 students.",
        "Set up and supervise laboratory experiments ensuring safety protocols.",
        "Prepare students for NEB board examinations and competitive entrance exams.",
        "Develop and grade periodic assessments, assignments, and project work.",
        "Organize science exhibitions, quizzes, and Olympiad preparation sessions.",
        "Stay updated with curriculum changes and integrate modern teaching methods.",
        "Collaborate with the Science department on curriculum development and lab inventory.",
      ],
      addedOn: "2026-04-20",
      expiresOn: "2026-06-30",
      isActive: true,
    },
    {
      id: 3,
      title: "English Language Teacher",
      category: "Teaching",
      level: "Primary Level (Grade 1-5)",
      experience: "Minimum 1 year of teaching English; Montessori training preferred",
      salary: "Negotiable (Based on experience and qualification)",
      vacancies: 2,
      workstation: "Naxal, Sanogaucharan, Kathmandu",
      responsibilities: [
        "Teach English language and literature using interactive and communicative methods.",
        "Focus on developing reading, writing, speaking, and listening skills.",
        "Organize storytelling, drama, and English club activities for students.",
        "Prepare and grade creative writing assignments, comprehension tests, and oral assessments.",
        "Create a positive and encouraging classroom environment for language learning.",
        "Communicate regularly with parents regarding student language development.",
      ],
      addedOn: "2026-05-05",
      expiresOn: "2026-06-20",
      isActive: true,
    },
    {
      id: 4,
      title: "Computer Science Teacher",
      category: "Teaching",
      level: "Secondary and Higher Secondary",
      experience: "Minimum 2 years of teaching programming and computer science",
      salary: "Negotiable (Based on experience and qualification)",
      vacancies: 1,
      workstation: "Naxal, Sanogaucharan, Kathmandu",
      responsibilities: [
        "Teach Computer Science including programming (Python, C), web development, and database concepts.",
        "Conduct practical lab sessions and guide students in project development.",
        "Prepare students for NEB practical and theory board examinations.",
        "Manage and maintain the school's computer lab including hardware and software updates.",
        "Organize coding clubs, hackathons, and tech awareness programs.",
        "Mentor students for national-level IT competitions and Olympiads.",
        "Integrate ICT tools into classroom teaching and assist other teachers with technology.",
      ],
      addedOn: "2026-05-10",
      expiresOn: "2026-06-25",
      isActive: true,
    },
    {
      id: 5,
      title: "Administrative Assistant",
      category: "Administration",
      level: "Entry Level",
      experience: "Minimum 1 year of administrative experience; school experience preferred",
      salary: "NPR 25,000-35,000 per month (Based on experience)",
      vacancies: 1,
      workstation: "Naxal, Sanogaucharan, Kathmandu",
      responsibilities: [
        "Manage front desk operations including visitor reception and phone calls.",
        "Maintain student records, attendance registers, and administrative files.",
        "Assist the Principal and Vice Principal with correspondence, scheduling, and reporting.",
        "Coordinate with parents regarding admissions, fee payments, and general inquiries.",
        "Manage office supplies inventory and place procurement requests.",
        "Support during school events, examinations, and parent-teacher meetings.",
        "Handle data entry and maintain the school management system database.",
      ],
      addedOn: "2026-05-15",
      expiresOn: "2026-06-10",
      isActive: true,
    },
    {
      id: 6,
      title: "Librarian",
      category: "Support Staff",
      level: "Entry Level",
      experience: "Diploma in Library Science; experience in school library preferred",
      salary: "NPR 20,000-30,000 per month",
      vacancies: 1,
      workstation: "Naxal, Sanogaucharan, Kathmandu",
      responsibilities: [
        "Manage day-to-day operations of the school library including book issuance and returns.",
        "Maintain the library catalog using digital library management software.",
        "Assist students and teachers in locating reference materials and research resources.",
        "Organize reading programs, book fairs, and author visit events.",
        "Procure new books, journals, and educational resources based on teacher recommendations.",
        "Ensure a quiet, welcoming, and organized library environment.",
        "Maintain inventory and conduct annual stock verification.",
      ],
      addedOn: "2026-04-25",
      expiresOn: "2026-06-05",
      isActive: true,
    },
  ],

  calendarEvents: [
    { id: 1, title: "New Year's Day (Rashtriya Topi Diwas)", type: "holiday", date: "2026-01-01", description: "Public holiday. School remains closed." },
    { id: 2, title: "Winter Vacation", type: "vacation", date: "2026-01-02", description: "Winter vacation continues." },
    { id: 3, title: "Winter Vacation", type: "vacation", date: "2026-01-05", description: "Winter vacation continues." },
    { id: 4, title: "Winter Vacation", type: "vacation", date: "2026-01-08", description: "Winter vacation continues." },
    { id: 5, title: "School Reopens After Winter Break", type: "event", date: "2026-01-12", description: "All students to report by 9:00 AM in full uniform." },
    { id: 6, title: "Staff Meeting", type: "event", date: "2026-01-13", description: "All teaching and administrative staff must attend." },
    { id: 7, title: "Martyr's Day (Shahid Diwas)", type: "holiday", date: "2026-01-30", description: "Public holiday commemorating Nepal's martyrs." },
    { id: 8, title: "Parent-Teacher Meeting (Grades 1-5)", type: "event", date: "2026-02-10", description: "Scheduled from 10:00 AM to 2:00 PM." },
    { id: 9, title: "Valentine's Day Celebration", type: "event", date: "2026-02-14", description: "Cultural program and card exchange activities." },
    { id: 10, title: "Maha Shivaratri", type: "holiday", date: "2026-02-26", description: "Public holiday for the festival of Lord Shiva." },
    { id: 11, title: "First Monthly Test (Grade 6-10)", type: "exam", date: "2026-02-27", description: "First monthly assessment test begins." },
    { id: 12, title: "International Women's Day", type: "event", date: "2026-03-08", description: "Special assembly and guest speaker program." },
    { id: 13, title: "Holi Celebration", type: "event", date: "2026-03-15", description: "Holi festivities. Half-day only." },
    { id: 14, title: "Fagu Purnima (Holi)", type: "holiday", date: "2026-03-16", description: "Public holiday for Holi." },
    { id: 15, title: "Academics: New Session Begins", type: "event", date: "2026-04-01", description: "New Academic Session 2083 formally inaugurated." },
    { id: 16, title: "Admissions Open for Academic Year 2083", type: "event", date: "2026-04-15", description: "Online and in-person application forms available." },
    { id: 17, title: "School Anniversary Day", type: "event", date: "2026-04-25", description: "Cultural program and awards ceremony." },
    { id: 18, title: "Labour Day", type: "holiday", date: "2026-05-01", description: "International Workers' Day. School closed." },
    { id: 19, title: "Buddha Jayanti", type: "holiday", date: "2026-05-21", description: "Public holiday celebrating Lord Buddha's birth." },
    { id: 20, title: "First Term Examination Begins", type: "exam", date: "2026-05-25", description: "First term examinations for Grade 1-12." },
    { id: 21, title: "First Term Examination Ends", type: "exam", date: "2026-06-05", description: "Last day of first term board exams." },
    { id: 22, title: "Result Declaration: First Term", type: "event", date: "2026-06-15", description: "Results published online and on notice board." },
    { id: 23, title: "Summer Vacation Begins", type: "vacation", date: "2026-06-20", description: "Summer break for all students and staff." },
    { id: 24, title: "Summer Vacation", type: "vacation", date: "2026-06-30", description: "Summer vacation continues." },
    { id: 25, title: "School Reopens After Summer", type: "event", date: "2026-07-15", description: "Students to report by 9:00 AM." },
    { id: 26, title: "Inter-House Sports Competition", type: "event", date: "2026-08-10", description: "Annual sports events between school houses." },
    { id: 27, title: "Teej Festival", type: "holiday", date: "2026-08-29", description: "Festival for women. School closed." },
    { id: 28, title: "Second Monthly Test (Grade 6-10)", type: "exam", date: "2026-09-05", description: "Second monthly assessment test." },
    { id: 29, title: "Shree Krishna Janmashtami", type: "holiday", date: "2026-09-15", description: "Festival. Half-day." },
    { id: 30, title: "Dashain Vacation Begins", type: "vacation", date: "2026-10-05", description: "Dashain holidays. School closed for 15 days." },
    { id: 31, title: "School Reopens After Dashain", type: "event", date: "2026-10-20", description: "Students report back after Dashain holidays." },
    { id: 32, title: "Tihar Vacation", type: "vacation", date: "2026-10-28", description: "Tihar holidays. School closed for 5 days." },
    { id: 33, title: "School Reopens After Tihar", type: "event", date: "2026-11-03", description: "Regular classes resume." },
    { id: 34, title: "Annual Sports Meet", type: "event", date: "2026-11-15", description: "Three-day athletic competition for all grades." },
    { id: 35, title: "Art & Science Exhibition", type: "event", date: "2026-11-28", description: "Students showcase projects and models." },
    { id: 36, title: "Second Term Examination Begins", type: "exam", date: "2026-12-05", description: "Second term board examinations for all grades." },
    { id: 37, title: "Second Term Examination Ends", type: "exam", date: "2026-12-18", description: "Last day of second term exams." },
    { id: 38, title: "Result Declaration: Second Term", type: "event", date: "2026-12-24", description: "Results published. Collect report cards." },
    { id: 39, title: "Christmas Day Celebration", type: "event", date: "2026-12-25", description: "Christmas program and carol singing." },
    { id: 40, title: "Winter Vacation Begins", type: "vacation", date: "2026-12-26", description: "Winter holidays. School closed." },
  ],
};
